print ("Hello, welcome to a simple program to find the average of three scores of students")
student1 = float(input("Please input the first score : "))
student2 = float(input("Please input the second score : "))
student3 = float(input("Please input the third score : "))
print ("Student scores:")
print (student1)
print (student2)
print (student3)
print ("Average:", (student1+student2+student3)/3)
