print ("Hello, welcome to a simple program to find the number of students and the leftover students in each group of each of the 3 classes ")
class1 = int(input("Please input the number of students in the first class as an int: "))
class2 = int(input("Please input the number of students in the second class as an int: "))
class3 = int(input("Please input the number of students in the third class as an int: "))
class1_group, class1_leftover = divmod(class1, 5)
class2_group, class2_leftover = divmod(class2, 7)
class3_group, class3_leftover = divmod(class3, 6)
print ("Number of students in each group:")
print ("Class 1 :", class1_group)
print ("Class 2 :", class2_group)
print ("Class 3 :", class3_group)
print ("Number of students leftover:")
print ("Class 1 :", class1_leftover)
print ("Class 2 :", class2_leftover)
print ("Class 3 :", class3_leftover)
